from __future__ import annotations
import argparse, json
from pathlib import Path
from .parser.excel_parser import parse_excel
from .parser.sfr_header_parser import parse_defines, correlate_field_macros
from .generator.lld_header_generator import generate_expected_decls, render_lld_header
from .patch.ast_lld_header_patcher import patch_lld_header
from .diff.sfr_diff_parser import parse_changed_macros, impacted_fields_from_macros
from .parser.lld_header_ast_parser import parse_lld_header


def main(argv=None):
    ap = argparse.ArgumentParser(description="Phase 7: existing sfr.h + Excel -> lld.h, AST update without markers")
    ap.add_argument("--excel", required=True, help="IP-XACT-like Excel workbook")
    ap.add_argument("--sfr-header", required=True, help="Existing sfr.h generated by another tool")
    ap.add_argument("--existing-lld", help="Existing lld.h to patch using AST declaration matching")
    ap.add_argument("--sfr-diff", help="git diff of old/new sfr.h; limits patch to impacted fields")
    ap.add_argument("--out", required=True, help="Output directory")
    ap.add_argument("--remove-stale", action="store_true", help="Reserved; default does not remove stale declarations")
    ap.add_argument("--llm-config", help="Path to LLM config JSON file to enable LLM generation")
    args = ap.parse_args(argv)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    fields = parse_excel(args.excel)
    
    # Filter out fields marked as debug in description
    fields = [f for f in fields if "debug" not in f.description.lower()]
    
    defines = parse_defines(args.sfr_header)
    macro_map = {f.key: correlate_field_macros(defines, f.ip, f.reg, f.field) for f in fields}
    decls, sem_report = generate_expected_decls(fields, macro_map, llm_config_path=args.llm_config)

    expected_path = out / "expected_lld.h"
    expected_path.write_text(render_lld_header(decls, sfr_include=Path(args.sfr_header).name), encoding="utf-8")
    (out / "semantic_report.json").write_text(json.dumps(sem_report, indent=2), encoding="utf-8")

    result = {"expected_lld": str(expected_path), "api_count": len(decls)}
    changed_macros = parse_changed_macros(args.sfr_diff) if args.sfr_diff else set()
    impacted = impacted_fields_from_macros(changed_macros) if changed_macros else None
    if args.existing_lld:
        _text, _nodes = parse_lld_header(args.existing_lld)
        ast_index = {name: {"return_type": n.return_type, "args": n.args, "start": n.start, "end": n.end} for name, n in _nodes.items()}
        (out / "ast_declaration_index.json").write_text(json.dumps(ast_index, indent=2), encoding="utf-8")
        patched_path = out / "patched_lld.h"
        support_preamble = "#include <stdint.h>\n#include \"" + Path(args.sfr_header).name + "\"\n#ifndef LLD_REG32\n#define LLD_REG32(base, offset) (*(volatile uint32_t *)((uintptr_t)(base) + (uintptr_t)(offset)))\n#endif"
        patch_report = patch_lld_header(args.existing_lld, decls, patched_path, impacted_fields=impacted, support_preamble=support_preamble)
        result["patched_lld"] = str(patched_path)
        result["patch_report"] = patch_report
        (out / "patch_report.json").write_text(json.dumps(patch_report, indent=2), encoding="utf-8")
    else:
        # First-time generation mode
        lld_path = out / "lld.h"
        lld_path.write_text(render_lld_header(decls, sfr_include=Path(args.sfr_header).name), encoding="utf-8")
        result["lld"] = str(lld_path)
        result["mode"] = "first_time_generation"

    (out / "run_report.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
